include:
  - 'https://gitlab.sib.fr/megalis/megalis-template/raw/master/.docker-template.yml'

stages:
  - test
  - mvn_build
  - build
  - deploy
  
mvnTest:
  image : maven:3.6.2-jdk-8
  stage : test
  script :
    - mvn -U test

mvnDeploy:
  image : maven:3.6.2-jdk-8
  stage : mvn_build
  only:
    - master
    - develop
    - tags
    - /^feature.*$/
    - /^hotfix.*$/
  script :
    - mvn -U clean deploy -DskipTests=true

buildSocleEsb:
  extends: .build
  variables:
    BUILD_CONTEXT: "myec3-socle-esb"
    IMAGE_NAME: "megalis/socle-esb"

buildSocleSynchro:
  extends: .build
  variables:
    BUILD_CONTEXT: "myec3-socle-synchro-module/myec3-socle-synchro"
    IMAGE_NAME: "megalis/socle-synchro"

buildSocleWebapp:
  extends: .build
  variables:
    BUILD_CONTEXT: "myec3-socle-webapp-module/myec3-socle-webapp"
    IMAGE_NAME: "megalis/socle-webapp"

deployWebapp:
  extends: .deployInteg
  variables:
    STACK_NAME: "socle-webapp"

deploySynchro:
  extends: .deployInteg
  variables:
    STACK_NAME: "socle-synchro"

deployEsb:
  extends: .deployInteg
  variables:
    STACK_NAME: "socle-esb"


deployPreprodWebapp:
  extends: .deployPreprod
  variables:
    STACK_NAME: "socle-webapp"
    

deployPreprodSynchro:
  extends: .deployPreprod
  variables:
    STACK_NAME: "socle-synchro"

deployPreprodEsb:
  extends: .deployPreprod
  variables:
    STACK_NAME: "socle-esb"
    
 
deployPreprodWebappManual:
  extends: .deployPreprodManual
  variables:
    STACK_NAME: "socle-webapp"
    

deployPreprodSynchroManual:
  extends: .deployPreprodManual
  variables:
    STACK_NAME: "socle-synchro"

deployPreprodEsbManual:
  extends: .deployPreprodManual
  variables:
    STACK_NAME: "socle-esb"
     
    
deployProdWebapp:
  extends: .deployProd
  variables:
    STACK_NAME: "socle-webapp"

deployProdSynchro:
  extends: .deployProd
  variables:
    STACK_NAME: "socle-synchro"

deployProdEsb:
  extends: .deployProd
  variables:
    STACK_NAME: "socle-esb"
