include:
  - /gitlab-ci/build.gitlab-ci.yml

stages:
  - test
  - sonar
  - mvn_build
  - build 
  - deploy

mvnTest:
  image : maven:3.6.2-jdk-8
  stage : test
  script :
    - mvn test

sonarqube-check:
  only:
    - master
  before_script: []
  stage: sonar
  image: maven:3.6.2-jdk-8
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify -DskipTests=true sonar:sonar -Dhttps.proxyHost=${PROXY_HOST} -Dhttps.proxyPort=${PROXY_PORT}
  allow_failure: true

buildSocleEsb:
  extends: .maven-build
  stage: mvn_build
  variables:
    BUILD_CONTEXT: "myec3-socle-esb"

buildSocleSynchro:
  extends: .maven-build
  stage: mvn_build
  variables:
    BUILD_CONTEXT: "myec3-socle-synchro-module/myec3-socle-synchro"

buildSocleWebapp:
  extends: .maven-build
  stage: mvn_build
  variables:
    BUILD_CONTEXT: "myec3-socle-webapp-module/myec3-socle-webapp"


buildimageSocleEsb:
  extends: .build
  stage: build
  variables:
    BUILD_CONTEXT: "myec3-socle-esb"
    IMAGE_NAME: "megalis/socle-esb"

buildimageSocleSynchro:
  extends: .build
  stage: build
  variables:
    BUILD_CONTEXT: "myec3-socle-synchro-module/myec3-socle-synchro"
    IMAGE_NAME: "megalis/socle-synchro"

buildimageSocleWebapp:
  extends: .build
  stage: build
  variables:
    BUILD_CONTEXT: "myec3-socle-webapp-module/myec3-socle-webapp"
    IMAGE_NAME: "megalis/socle-webapp"

deployWebapp:
  extends: .deployInteg
  stage: deploy
  variables:
    STACK_NAME: "socle-webapp"

deploySynchro:
  extends: .deployInteg
  stage: deploy
  variables:
    STACK_NAME: "socle-synchro"

deployEsb:
  extends: .deployInteg
  stage: deploy
  variables:
    STACK_NAME: "socle-esb"


deployPreprodWebapp:
  extends: .deployPreprod
  stage: deploy
  variables:
    STACK_NAME: "socle-webapp"
    

deployPreprodSynchro:
  extends: .deployPreprod
  stage: deploy
  variables:
    STACK_NAME: "socle-synchro"

deployPreprodEsb:
  extends: .deployPreprod
  stage: deploy
  variables:
    STACK_NAME: "socle-esb"
    
 
deployPreprodWebappManual:
  extends: .deployPreprodManual
  stage: deploy
  variables:
    STACK_NAME: "socle-webapp"
    

deployPreprodSynchroManual:
  extends: .deployPreprodManual
  stage: deploy
  variables:
    STACK_NAME: "socle-synchro"

deployPreprodEsbManual:
  extends: .deployPreprodManual
  stage: deploy
  variables:
    STACK_NAME: "socle-esb"
     
    
deployProdWebapp:
  extends: .deployProd
  stage: deploy
  variables:
    STACK_NAME: "socle-webapp"

deployProdSynchro:
  extends: .deployProd
  stage: deploy
  variables:
    STACK_NAME: "socle-synchro"

deployProdEsb:
  extends: .deployProd
  stage: deploy
  variables:
    STACK_NAME: "socle-esb"
