image: alpine:latest

before_script:
  - export http_proxy=http://pro01.sib.fr:3128
  - export https_proxy=http://pro01.sib.fr:3128
  - export no_proxy=sib.fr
  - apk update && apk add sshpass openssh-client bash
  
  - build
  - buildImages
  - deploy_dev
  - deploy_preprod

build:
  image : docker:stable-dind
  stage: build
  script:
    - docker build -f Dockerfile_mvn.stages .

buildImages :
  image: docker:stable-dind
  stage: buildImage
  script:
    - docker build -f Dockerfile_esb.stages -t klask.sib.fr:52100/megalis/socle-esb .
    - docker build -f Dockerfile_esb.stages -t klask.sib.fr:52100/megalis/socle-esb:${CI_COMMIT_SHA:0:8} .
    - docker push klask.sib.fr:52100/megalis/socle-esb
    - docker push klask.sib.fr:52100/megalis/socle-esb:${CI_COMMIT_SHA:0:8}
    - docker build -f Dockerfile_webapp.stages -t klask.sib.fr:52100/megalis/socle-webapp .
    - docker build -f Dockerfile_webapp.stages -t klask.sib.fr:52100/megalis/socle-webapp:${CI_COMMIT_SHA:0:8} .
    - docker push klask.sib.fr:52100/megalis/socle-webapp
    - docker push klask.sib.fr:52100/megalis/socle-webapp:${CI_COMMIT_SHA:0:8}
    - docker build -f Dockerfile_synchro.stages -t klask.sib.fr:52100/megalis/socle-synchro .
    - docker build -f Dockerfile_synchro.stages -t klask.sib.fr:52100/megalis/socle-synchro:${CI_COMMIT_SHA:0:8} .
    - docker push klask.sib.fr:52100/megalis/socle-synchro
    - docker push klask.sib.fr:52100/megalis/socle-synchro:${CI_COMMIT_SHA:0:8}
    - docker build -f Dockerfile_ws.stages -t klask.sib.fr:52100/megalis/socle-ws .
    - docker build -f Dockerfile_ws.stages -t klask.sib.fr:52100/megalis/socle-ws:${CI_COMMIT_SHA:0:8} .
    - docker push klask.sib.fr:52100/megalis/socle-ws
    - docker push klask.sib.fr:52100/megalis/socle-ws:${CI_COMMIT_SHA:0:8}


deploy_dev:
  stage: deploy_dev
  script:
    - sshpass -V
    - export SSHPASS=centos
    - sshpass -e ssh -o StrictHostKeyChecking=no root@sangoku.sib.fr "export URL_DOCKER=klask.sib.fr:52100;docker stack deploy --with-registry-auth -c /sillage/megalis/megalis-stack.yml megalis"

deploy_preprod:
  image: docker:stable-dind
  stage: deploy_preprod
  script:
    - docker build -f Dockerfile_webapp.stages -t klask.sib.fr:5000/megalis/socle-webapp .
    - docker push klask.sib.fr:5000/megalis/socle-webapp
    - sshpass -V
    - export SSHPASS=7rEjdDLFyE
    - sshpass -e ssh -o StrictHostKeyChecking=no root@10.253.104.100 "export URL_DOCKER=haproxy-edipro.sib.fr:443;docker stack deploy --with-registry-auth -c /data/livraison/megalis-stack.yml megalis"
  when: manual

