image: alpine:latest

before_script:
  - export http_proxy=http://pro01.sib.fr:3128
  - export https_proxy=http://pro01.sib.fr:3128
  - export no_proxy=sib.fr
  - apk update && apk add sshpass openssh-client bash

stages:
  - mvn_deploy
  - build
  - deploy

build:
  image : maven:3-jdk-8
  stage : mvn_deploy
  script :
    - mvn -B deploy

buildSocleESB_dev:
  image: docker:stable-dind
  stage: build
  only:
    - develop
  variables:
    DOCKER_FILE: "myec3-socle/myec3-socle-esb/Dockerfile_esb.stages"
    CI_REGISTRY_IMAGE: "klask.sib.fr:52100/megalis/socle-esb/develop"
  script:
    - docker build -f ${DOCKER_FILE} -t ${CI_REGISTRY_IMAGE} .
    - docker tag ${CI_REGISTRY_IMAGE} ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}
    - echo "push ${CI_REGISTRY_IMAGE}:latest" && docker push ${CI_REGISTRY_IMAGE}:latest
    - echo "push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}" && docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}

buildSocleESB_preprod:
  image: docker:stable-dind
  stage: build
  only:
    - master
  variables:
    DOCKER_FILE: "myec3-socle/myec3-socle-esb/Dockerfile_esb.stages"
    CI_REGISTRY_IMAGE_PUBLIC: "klask.sib.fr:5000/megalis/socle-esb/master"
  script:
    - docker build -f ${DOCKER_FILE} -t ${CI_REGISTRY_IMAGE_PUBLIC} .
    - echo "push ${CI_REGISTRY_IMAGE_PUBLIC}:latest" && docker push ${CI_REGISTRY_IMAGE_PUBLIC}:latest

buildSocleSynchro_dev:
  image: docker:stable-dind
  stage: build
  only:
    - develop
  variables:
    DOCKER_FILE: "myec3-socle-synchro-module/myec3-socle-synchro/Dockerfile.stages"
    CI_REGISTRY_IMAGE: "klask.sib.fr:52100/megalis/socle-synchro/develop"
  script:
    - docker build -f ${DOCKER_FILE} -t ${CI_REGISTRY_IMAGE} .
    - docker tag ${CI_REGISTRY_IMAGE} ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}
    - echo "push ${CI_REGISTRY_IMAGE}:latest" && docker push ${CI_REGISTRY_IMAGE}:latest
    - echo "push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}" && docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}

buildSocleSynchro_preprod:
  image: docker:stable-dind
  stage: build
  only:
    - master
  variables:
    DOCKER_FILE: "myec3-socle-synchro-module/myec3-socle-synchro/Dockerfile.stages"
    CI_REGISTRY_IMAGE_PUBLIC: "klask.sib.fr:5000/megalis/socle-synchro/master"
  script:
    - docker build -f ${DOCKER_FILE} -t ${CI_REGISTRY_IMAGE_PUBLIC} .
    - echo "push ${CI_REGISTRY_IMAGE_PUBLIC}:latest" && docker push ${CI_REGISTRY_IMAGE_PUBLIC}:latest

buildSocleWebapp_dev:
  image: docker:stable-dind
  stage: build
  only:
    - develop
  variables:
    DOCKER_FILE: "myec3-socle-webapp-module/myec3-socle-webapp/Dockerfile.stages"
    CI_REGISTRY_IMAGE: "klask.sib.fr:52100/megalis/socle-webapp/develop"
  script:
    - docker build -f ${DOCKER_FILE} -t ${CI_REGISTRY_IMAGE} .
    - docker tag ${CI_REGISTRY_IMAGE} ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}
    - echo "push ${CI_REGISTRY_IMAGE}:latest" && docker push ${CI_REGISTRY_IMAGE}:latest
    - echo "push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}" && docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}

buildSocleWebapp_preprod:
  image: docker:stable-dind
  stage: build
  only:
    - master
  variables:
    DOCKER_FILE: "myec3-socle-webapp-module/myec3-socle-webapp/Dockerfile.stages"
    CI_REGISTRY_IMAGE_PUBLIC: "klask.sib.fr:5000/megalis/socle-webapp/master"
  script:
    - docker build -f ${DOCKER_FILE} -t ${CI_REGISTRY_IMAGE_PUBLIC} .
    - echo "push ${CI_REGISTRY_IMAGE_PUBLIC}:latest" && docker push ${CI_REGISTRY_IMAGE_PUBLIC}:latest

deploy_dev:
  stage: deploy
  only:
    - develop
  script:
    - ssh megalis@sangoku.sib.fr "/sillage/megalis/deploy.sh socle develop ${CI_COMMIT_SHA:0:8}"

deploy_preprod:
  stage: deploy
  only:
    - master
  script:
    - ssh megalis@10.253.104.100 "/data/livraison/deploy.sh socle preprod"
  when: manual
