include:
  - 'https://gitlab.sib.fr/megalis/megalis-template/raw/master/.docker-template.yml'

stages:
  - mvn_deploy
  - build
  - deploy

mvnDeploy:
  image : maven:3-jdk-8
  stage : mvn_deploy
  script :
    - mvn -B deploy

buildSocleEsb:
  extends: .build
  variables:
    BUILD_CONTEXT: "myec3-socle-esb"
    IMAGE_NAME: "megalis/socle-esb"

buildSocleSynchro:
  extends: .build
  variables:
    BUILD_CONTEXT: "myec3-socle-synchro-module/myec3-socle-synchro"
    IMAGE_NAME: "megalis/socle-synchro"

buildSocleWebapp:
  extends: .build
  variables:
    BUILD_CONTEXT: "myec3-socle-webapp-module/myec3-socle-webapp"
    IMAGE_NAME: "megalis/socle-webapp"

deployWebapp:
  extends: .deployDev
  variables:
    STACK_NAME: "socle-webapp"

deploySynchro:
  extends: .deployDev
  variables:
    STACK_NAME: "socle-synchro"

deployEsb:
  extends: .deployDev
  variables:
    STACK_NAME: "socle-esb"


deployPreprodWebapp:
  extends: .deployPreprod
  variables:
    STACK_NAME: "socle-webapp"
    
deployPreprodWebapp:on-schedule:
  extends: .deployPreprod:on-schedule
  variables:
    STACK_NAME: "socle-webapp"

deployPreprodSynchro:
  extends: .deployPreprod
  variables:
    STACK_NAME: "socle-synchro"

deployPreprodEsb:
  extends: .deployPreprod
  variables:
    STACK_NAME: "socle-esb"

deployProdWebapp:
  extends: .deployProd
  variables:
    STACK_NAME: "socle-webapp"

deployProdSynchro:
  extends: .deployProd
  variables:
    STACK_NAME: "socle-synchro"

deployProdEsb:
  extends: .deployProd
  variables:
    STACK_NAME: "socle-esb"
