image: alpine:latest

before_script:
  - export http_proxy=http://pro01.sib.fr:3128
  - export https_proxy=http://pro01.sib.fr:3128
  - export no_proxy=sib.fr
  - apk update && apk add sshpass openssh-client bash
  
stages:
  - build
  - deploy_dev
  - deploy_preprod


build:
  image: docker:stable-dind
  stage: build
  script:
    - docker build -f Dockerfile.stages -t klask.sib.fr:52100/megalis/socle-webapp .
    - docker build -f Dockerfile.stages -t klask.sib.fr:52100/megalis/socle-webapp:${CI_COMMIT_SHA:0:8} .
    - docker push klask.sib.fr:52100/megalis/socle-webapp
    - docker push klask.sib.fr:52100/megalis/socle-webapp:${CI_COMMIT_SHA:0:8}

deploy_dev:
  stage: deploy_dev
  script:
    - sshpass -V
    - export SSHPASS=centos
    - sshpass -e ssh -o StrictHostKeyChecking=no root@sangoku.sib.fr "docker stack deploy --with-registry-auth -c /sillage/megalis/megalis-stack.yml megalis"

deploy_preprod:
  stage: deploy_preprod
  script:
    - echo "Deploy to pre-production server"
  environment:
    name: production
    url: https://example.com
  when: manual
#  only:
#    - master