include:
  - 'https://gitlab.sib.fr/megalis/megalis-template/raw/master/.docker-template.yml'

stages:
  - test
  - sonar
  - mvn_build
  - build 
  - deploy

mvnTest:
  image : maven:3.6.2-jdk-8
  stage : test
  script :
    - mvn test


mvnDeploy:
  image : maven:3.6.2-jdk-8
  stage : mvn_build
  only:
    - master
    - develop
    - tags
    - /^feature.*$/
    - /^hotfix.*$/
  script :
    - mvn deploy -DskipTests=true
    
sonarqube-check:
  only:
    - master
  before_script: []
  stage: sonar
  image: maven:3.6.2-jdk-8
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify -DskipTests=true sonar:sonar -Dhttps.proxyHost=${PROXY_HOST} -Dhttps.proxyPort=${PROXY_PORT}
  allow_failure: true


buildSocleEsb:
  extends: .build
  variables:
    BUILD_CONTEXT: "myec3-socle-esb"
    IMAGE_NAME: "megalis/socle-esb"

buildSocleSynchro:
  extends: .build
  variables:
    BUILD_CONTEXT: "myec3-socle-synchro-module/myec3-socle-synchro"
    IMAGE_NAME: "megalis/socle-synchro"

buildSocleWebapp:
  extends: .build
  variables:
    BUILD_CONTEXT: "myec3-socle-webapp-module/myec3-socle-webapp"
    IMAGE_NAME: "megalis/socle-webapp"

deployWebapp:
  extends: .deployInteg
  variables:
    STACK_NAME: "socle-webapp"

deploySynchro:
  extends: .deployInteg
  variables:
    STACK_NAME: "socle-synchro"

deployEsb:
  extends: .deployInteg
  variables:
    STACK_NAME: "socle-esb"


deployPreprodWebapp:
  extends: .deployPreprod
  variables:
    STACK_NAME: "socle-webapp"
    

deployPreprodSynchro:
  extends: .deployPreprod
  variables:
    STACK_NAME: "socle-synchro"

deployPreprodEsb:
  extends: .deployPreprod
  variables:
    STACK_NAME: "socle-esb"
    
 
deployPreprodWebappManual:
  extends: .deployPreprodManual
  variables:
    STACK_NAME: "socle-webapp"
    

deployPreprodSynchroManual:
  extends: .deployPreprodManual
  variables:
    STACK_NAME: "socle-synchro"

deployPreprodEsbManual:
  extends: .deployPreprodManual
  variables:
    STACK_NAME: "socle-esb"
     
    
deployProdWebapp:
  extends: .deployProd
  variables:
    STACK_NAME: "socle-webapp"

deployProdSynchro:
  extends: .deployProd
  variables:
    STACK_NAME: "socle-synchro"

deployProdEsb:
  extends: .deployProd
  variables:
    STACK_NAME: "socle-esb"
